### ISSUE TITLE
Too large files

### ISSUE THREAD

**Issue by doktorpixel14** [Microsoft/USBuildingFootprints#10]
Would it be possible to also create smaller .json files for smaller parts of the state or even cities? Because large files like CA, FL or OH are very difficult to read without special tools (that I'm not aware of).

**Comment by RussNelson** [comment]
They are structured such that each building is on a line of its own, so you can:

#!/bin/sh
head -1 $1
grep '[longitude\.fraction.*,latitude\.fraction' $1
tail -2 $1

to get a subset of the data.

**Comment by rbrundritt** [comment]
If you want to take a peak at the data you can use Powershell with this command:

`Get-Content Washington.json | select -First 10`


Change "Washington.json" to the name of the file you are looking at and change "10" to the number of lines you want to see in the file. You can also do -Last if you want to look at the end of the file. You can also skip lines like this:

`Get-Content Washington.json | select -skip 4 -First 10`

**Comment by chrisbnyc** [comment]
Some other options are discussed at this page here: 

[GIS.stackexchange.com](https://gis.stackexchange.com/questions/16340/alternatives-to-ogr2ogr-for-loading-large-geojson-files-to-postgis)

Basically, with a combination of vim and the shell you can strip the header/footer off of the .json file, split them, and then re-insert headers and footers to each segment.  Using this technique I converted CA to a shapefile with no problems, so opening up the .json should be fine.

**Comment by iandees** [comment]
I split up the buildings by Census tract (more manageable than whole states) and dropped 8 of the 15 decimal points of precision. You can download them gzipped by state (https://s3.amazonaws.com/data.openstreetmap.us/bingbuildings/bystate/27.tar.gz) or by individual tract (https://s3.amazonaws.com/data.openstreetmap.us/bingbuildings/bytract/27/27139081100.geojson).

**Comment by nickpeihl** [comment]
I created [this jq script](https://gist.github.com/nickpeihl/14df1b3964381c70834dea5c0a2a6df6) to convert a GeoJSON FeatureCollection into one feature per line. This worked for me on the Washington dataset, however, I haven't tried any of the others. This makes it easier to use streaming tools like `head`, `tail`, or `grep` to create subsets of the data.

https://stedolan.github.io/jq/

**Comment by jharpster** [comment]
Looks like there are some solutions to this. Thanks all.
