### ISSUE TITLE
Boundary Effects

### ISSUE THREAD

**Issue by simonjchapman** [Microsoft/USBuildingFootprints#13]
The team that produces these footprints should be congratulated for their efforts. A truely amazing piece of work.

There are, however, some boundary effects where there are missing footprints. These seems to tiles that have not gone through the analysis. You can see it in the Bay Area of San Francisco, and, for example, around Philadelphia in the following screenshots:

![footprints boundary effect](https://user-images.githubusercontent.com/40736226/42134555-fa78dc2e-7d0b-11e8-98df-5db1e8bd355d.png)

![footprints boundary effect zoom](https://user-images.githubusercontent.com/40736226/42134561-0de89970-7d0c-11e8-9f2e-c3d5e8d92e7e.png)

Is there a reason they are missing, and will they be added in the future?

Thanks in advace,
Simon.

**Comment by chrisbnyc** [comment]
+1 on this, would love it (if possible) for the missing tiles to be included.  This data is great to have, thanks again!

**Comment by nitrif** [comment]
Thanks @simonjchapman for pointing this out. I'll follow up unce we track this down.

**Comment by nmpeterson** [comment]
FWIW, this is a problem in Chicago, too.

![2018-07-02_9-46-28](https://user-images.githubusercontent.com/4383272/42170751-0cf82b12-7ddd-11e8-8586-e4d9b60fc9bf.png)

**Comment by vvascanus** [comment]
There are also tile-shaped gaps all along I-15 in Connecticut.

**Comment by chrisbnyc** [comment]
I've looked at several states, it appears to be any major metropolitan area has these gaps.  I'd imagine it is something in the workflow that will be fixed for all when one is fixed.

**Comment by nitrif** [comment]
The gap areas contain image tiles taken with different cameras, which is causing the creation of artificial edges between neighboring tiles. These confuse our detection network which hasn't learned to deal with them.
We took a very conservative approach of skipping such tiles. I think we could add aditional effort in order to properly deal with this problem.

**Comment by simonjchapman** [comment]
Very interesting. Might it be good to relax your approach and output these tiles as a "delta"? That would also allow members of this group to help you with validating their quality and also not disrupt the integrity of the currently published set.

Thanks again for your efforts in this area.

**Comment by nitrif** [comment]
Fixed in the latest release.

**Comment by antifa-ev** [comment]
@simonjchapman How have you generated your renderings? I'm looking for the right software ...

**Comment by chrisbnyc** [comment]
In at least the San Jose example, it looks like it is being too conservative for the edge of I-880: 

<img width="849" alt="image" src="https://user-images.githubusercontent.com/1864838/42909994-e396062a-8ab3-11e8-953d-9bb355da9f9b.png">

looks like it tracks to the 101 just fine but there's a nice hard edge on the imagery (used by Apple Maps)

**Comment by ajblen13** [comment]
Great work pulling this all together. Just wanted to make you aware that we're seeing similar issues near Minneapolis/St. Paul.
![bldg_footprints](https://user-images.githubusercontent.com/41588552/43091601-0649eada-8e9a-11e8-8dea-ccaa19cc209d.PNG)

**Comment by Kmthenry** [comment]
Incredible dataset! Likewise, Louisville Kentucky. 
![capture2](https://user-images.githubusercontent.com/41696766/43212241-72914bee-9001-11e8-9f08-e262b4ec7340.JPG)
