### ISSUE TITLE
Required member "properties" missing from feature objects

### ISSUE THREAD

**Issue by grovduck** [Microsoft/USBuildingFootprints#15]
Tremendous resource.  Thank you for this ...

I just downloaded the DC example and, in looking at the GeoJSON, all feature objects are missing the member "properties" as a requirement (at least according to the GeoJSON spec 3.2).

> A Feature object has a member with the name "properties".  The value of the properties member is an object (any JSON object or a JSON null value)

I know at least http://geojson.io is throwing an error with the GeoJSON files:

> Invalid JSON file: TypeError: Cannot convert undefined or null to object

Any possibility of adding `"properties":{}` to each feature object?

**Comment by mikelmaron** [comment]
@grovduck I had luck using  [jq](https://stedolan.github.io/jq/)

`jq '.features[] = (.features[] + {"properties": {}})'`

**Comment by mikelmaron** [comment]
Spoke too soon. That jq command works on a small file, but still grappling with gettin jq to work on a large file....

**Comment by worace** [comment]
:+1: to this issue -- it is a minor request but would be great if future releases included the `properties` key.

@mikelmaron you might have better luck using 2 separate jq steps, one to extract the features and one to add the `properties` key. I think the way listed above requires loading all of the data into memory and doing updates in place, which takes a lot of RAM for the bigger files. The above command didn't finish for me on the CA dataset after several minutes, whereas this ran in about 4 minutes:

```
jq -cr .features[] California.json | jq -cr ". + {\"properties\": {}}" | wc -l
10556550
```

**Comment by jharpster** [comment]
This is updated at the 1.1 release.

**Comment by antifa-ev** [comment]
@nitrif The error from #30 has vanished, but now all the GeoJSON segfault tippecanoe when they exceed 49.9 % progress. See also https://github.com/mapbox/tippecanoe/issues/608
