### ISSUE TITLE
Height Data?

### ISSUE THREAD

**Issue by XPav** [Microsoft/USBuildingFootprints#19]
A quick extract for my county (Nevada County, CA) shows that there's no height data.  Is there height data for other locations, or is it not present for anything?

**Comment by RussNelson** [comment]
None for NY.

**Comment by nitrif** [comment]
There is no height data present.

**Comment by jsdunn50** [comment]
Morning

It would be nice to join some attributes to the footprint data. Is there any work ongoing in this area ? 

Regards.

Jeremy.

**Comment by jharpster** [comment]
@jsdunn50 There is currently no work planned for joining attributes to building footprints.
