### ISSUE TITLE
some polygons invalid

### ISSUE THREAD

**Issue by darkblue-b** [Microsoft/USBuildingFootprints#20]
after importing the **California** json set into PostGIS, testing for ST_Valid(geom) returns 193 invalids out of 10556550 rows.

[msft_bldgs_invalids.tsv.zip](https://github.com/Microsoft/USBuildingFootprints/files/2157152/msft_bldgs_invalids.tsv.zip)

`POSTGIS="2.4.3" PGSQL="100" GEOS="3.6.2-CAPI-1.10.2 4d2925d6" PROJ="Rel. 4.9.3, 15 August 2016" GDAL="GDAL 2.3.1, released 2018/06/22" LIBXML="2.9.3" LIBJSON="0.11.99" LIBPROTOBUF="1.2.1" `

`ogr2ogr -dim 2 -lco GEOMETRY_NAME=geom -lco SCHEMA=public -nln msft_ca_jun18 -nlt POLYGON  -lco FID=gid -f PostgreSQL PG:dbname=msft_bldgs California.json -t_srs EPSG:4326`

`msft_bldgs-# COPY (select gid, st_asgeojson(geom) as geom from msft_ca_jun18 where not st_isvalid(geom)) to '/tmp/msft_bldgs_invalids.tsv' ;`

**Comment by jsdunn50** [comment]
Interesting

So 0.00183% of them are invalid ? 

Regards. 

Jeremy.

**Comment by nitrif** [comment]
We should have this check in place. We'll try it against the samples you provided and fix.
Thanks.

**Comment by darkblue-b** [comment]
ah great news -- btw I like this paper on the topic fyi
```
About Invalid, Valid and Clean Polygons
Peter van Oosterom, Wilko Quak and Theo Tijssen
Delft University of Technology, The Netherlands
```

**Comment by nitrif** [comment]
Fixed in the latest release.

**Comment by darkblue-b** [comment]
team - new set of bldgs data for California shows an increase in these invalids   feb-2019
