### ISSUE TITLE
Large gap in data around Chicago

### ISSUE THREAD

**Issue by stevevance** [Microsoft/USBuildingFootprints#22]
I see a large gap in buildings around the City of Chicago, Illinois. Does anyone else see this?

![image 1](https://user-images.githubusercontent.com/1330459/42238004-23120d3a-7ec5-11e8-97cb-823becb0381c.png)

**Comment by nmpeterson** [comment]
This was already flagged as part of a broader issue in #13 (specifically https://github.com/Microsoft/USBuildingFootprints/issues/13#issuecomment-401831290)

**Comment by nitrif** [comment]
This is the duplicate. Closing.
