### ISSUE TITLE
actual count of building footprints

### ISSUE THREAD

**Issue by gboeing** [Microsoft/USBuildingFootprints#25]
The readme says:

> This dataset contains 124,885,597 computer generated building footprints in all 50 US states.

However, when I load all the files, I find 122,608,100 total, which exactly matches the sum of the state-level counts in the table toward the bottom of the readme. So it appears the dataset actually contains 122,608,100 footprints, correct?

**Comment by jharpster** [comment]
It's possible. There was another 'other' for download that we did not include. These are mostly buildings at the edges of boundaries, in water and other edge cases. Its possible the final counts are a bit off.
