### ISSUE TITLE
Suggested Citation

### ISSUE THREAD

**Issue by npr99** [Microsoft/USBuildingFootprints#28]
I would like to cite this data source in a journal article. Do you have a recommended citation?

**Comment by jharpster** [comment]
Hi @npr99 I don't have a recommendation. I asked a copyeditor and they suggested:
Microsoft, Computer Vision Building Footprints (2018) GitHub Repository, https://github.com/Microsoft/USBuildingFootprints

Open to other suggestions if you have one.
