### ISSUE TITLE
Produce one giant GeoJSON

### ISSUE THREAD

**Issue by antifa-ev** [microsoft/USBuildingFootprints#33]
May you please also publish one giant GeoJSON (or any other format) for the whole US? Doing the merging on your own hardware is nearly impossible with a standard PC.

I have 32 GB of memory and was still unable to merge the geojsons with geojson-merge despite increasing the node heap limit to 30 GB.

**Comment by nitrif** [comment]
Hi @antifa-ev, each building polygon feature is placed in a separate line, so reading line by line from the state files and outputting to a single output file should use minimum memory. Just make sure to take into account few header and footer feature collection lines. If you need help with this, I would share a merge script.
