### ISSUE TITLE
Error to load California data

### ISSUE THREAD

**Issue by mattmar** [Microsoft/USBuildingFootprints#48]
I am not able to open California data, is anyone else having this problem?

**Comment by cognusion** [comment]
Works fine for me. When you say "open" it makes me think you're using some application to try to look at it all at once, which will likely require more resources than you have available.

**Comment by jharpster** [comment]
Hey @mattmar Some other folks posted a number of different solutions for opening the data over at: https://github.com/Microsoft/USBuildingFootprints/issues/35
