### ISSUE TITLE
missing blobs for TN, TX

### ISSUE THREAD

**Issue by pblack-trulia** [Microsoft/USBuildingFootprints#5]
seems like the link is broken for these two states after I run wget I get this:

`wget https://usbuildingdata.blob.core.windows.net/usbuildings/Texas.zip
--2018-06-28 14:12:01--  https://usbuildingdata.blob.core.windows.net/usbuildings/Texas.zip
Resolving usbuildingdata.blob.core.windows.net (usbuildingdata.blob.core.windows.net)... 13.93.168.80
Connecting to usbuildingdata.blob.core.windows.net (usbuildingdata.blob.core.windows.net)|13.93.168.80|:443... connected.
HTTP request sent, awaiting response... 404 The specified blob does not exist.
2018-06-28 14:12:01 ERROR 404: The specified blob does not exist..`

**Comment by andrewseidl** [comment]
Similarly Nevada links to Nebraska.

**Comment by sbreyer** [comment]
Any solution to the missing TN and TX files?

**Comment by jharpster** [comment]
This is a simple upload error. We will have the link fixed by 7/2

**Comment by pblack-trulia** [comment]
Thanks @jharpster and for all of your and your team's hard work on this amazing addition to the open source realm!

**Comment by sbreyer** [comment]
Awesome. thanks for the update. Really appreciate all the work to make this available!

**Comment by jharpster** [comment]
Fixed!
