### ISSUE TITLE
detial or reference of the polygonization method

### ISSUE THREAD

**Issue by sshuair** [Microsoft/USBuildingFootprints#51]
Is there anyone know the detial or reference of the polygonization method？
@jharpster  @nitrif Is that possible tell us some details?

**Comment by IoTGirl** [comment]
Please see the two stage process described on the blog at [https://blogs.bing.com/maps/2018-06/microsoft-releases-125-million-building-footprints-in-the-us-as-open-data/](https://blogs.bing.com/maps/2018-06/microsoft-releases-125-million-building-footprints-in-the-us-as-open-data/)

**Comment by NiklasDL** [comment]
@IoTGirl the blog does not tell anything more than this repository does.
