### ISSUE TITLE
More details about polygonization algorithm?

### ISSUE THREAD

**Issue by YpingHu** [microsoft/USBuildingFootprints#72]
Could you give more details about how this polygonization algorithm is implemented?  This repository tells us that the method tries to impose some of a priori building properties, but stops abruptly when tries to elaborate.

**Comment by nikolatr** [comment]
Hi @YpingHu, the polygonization algorithm is not public yet, and I am not sure how much may I reveal. I hope you understand.

**Comment by YpingHu** [comment]
> Hi @YpingHu, the polygonization algorithm is not public yet, and I am not sure how much may I reveal. I hope you understand.

OK, thanks!
