### ISSUE TITLE
Extract polygons for a specific city from State GeoJson

### ISSUE THREAD

**Issue by tljstewart** [microsoft/USBuildingFootprints#74]
Is there anyway to just extract specific state areas of polygons say for example for a City, FIPS code, Census Block Group, Region or any other?

For a concrete example; say for Florida you want polygons for Miami-Dade, the polygons in the GeoJson don't seem to have any specific order in the file, is there anyway to just get polygons for Miami-Dade?

**Comment by andwoi** [comment]
There are a couple tools you can use to extract for a specific AOI. Some that come to mind are SQL Server, QGIS, GeoPandas, and Spark + Sedona. You can increase performance by constructing a spatial index or using [quad keys](https://docs.microsoft.com/en-us/bingmaps/articles/bing-maps-tile-system). Hope that helps. We don't have plans to create smaller partitions.
