### ISSUE TITLE
enhancement: apply rounding to computer generated decimal precision

### ISSUE THREAD

**Issue by jgravois** [Microsoft/USBuildingFootprints#8]
unbelievably cool announcement!

if there's anywhere in your pipeline that you could rough up the [subatomic](https://gis.stackexchange.com/questions/8650/measuring-accuracy-of-latitude-and-longitude/8674#8674) coordinate precision, consumers everywhere would be much obliged. 

```json
{
  "type": "Feature",
  "geometry": {
    "type": "Polygon",
    "coordinates": [[
      [-162.29951646880551, 67.065383815817825],
      [-162.29952962664339, 67.065303662945269],
      [-162.29931058186409, 67.065298202629734],
      [-162.29929742402621, 67.065378355520338],
      [-162.29951646880551, 67.065383815817825]
    ]]
  }
} 
```

file this one under: :wink:	
![mouse](http://t1.gstatic.com/images?q=tbn:ANd9GcQIAH6RyctXaj9xHrKUOkRMbOmNBow51OlMZDi36je_2GCivAVI)

**Comment by rbrundritt** [comment]
I agree this would be good. Perhaps running a regular expression over each line of the file, since each line has all the data for a single building. Something like replacing "([0-9]+.[0-9]{6})[0-9]*" with "$1" would reduce the data down to 6 decimal places (~11cm).

**Comment by jharpster** [comment]
Thanks @jgravois (aka geogangster) we'll take a look at this in the pipeline.

**Comment by nitrif** [comment]
Thanks. We would rather not change the current data drop, but we'll include the rounding for all future updates.

**Comment by jharpster** [comment]
This is updated for the 1.1 release.

**Comment by jgravois** [comment]
much appreciated! :tada:
