### ISSUE TITLE
Documentation: date of imagery

### ISSUE THREAD

**Issue by kekscom** [Microsoft/USBuildingFootprints#9]
Hi, Awesome work!
Could you provide the data of imagery and / or capturing in the documentation?

**Comment by RussNelson** [comment]
They said that it comes from many different time periods, so it is quite difficult to say exactly what dates any one house came from.

**Comment by kekscom** [comment]
A year would be good enough :-)

**Comment by rbrundritt** [comment]
You could use the Bing Maps REST Imagery Metadata service to get a date range for the imagery. The range can be several years as the imagery is a combination of years. https://msdn.microsoft.com/en-US/library/ff701716.aspx

**Comment by kekscom** [comment]
The Metadata service would help.
Thanks!
